cache:
  paths:
  - node_modules/

stages:
- build
- test
- review
- production

build:
  image: node:12
  stage: build
  before_script:
  - if [ $CI_COMMIT_BRANCH="master" ]; then sed -i "s%DEFAULT_BACKEND_URL%$BACKEND_URL%g" .env.production;fi
  - cat .env.production
  script:
  - npm config set unsafe-perm true
  - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - cnpm install
  - npm run lint
  - npm run build
  - cp -f src/components/_mavon-editor@2.9.1@mavon-editor/dist/mavon-editor.js dist/_mavon-editor@2.9.1@mavon-editor/dist
  artifacts:
    paths:
    - dist/

test:
  image: node:12
  stage: test
  script:
  - npm config set unsafe-perm true
  - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - cnpm install -D
  - npm run test

review:
  stage: review
  image: registry.git.bdaa.pro:4567/yxonic/bdaa-deploy-image:v3.0.2
  before_script:
  - helm repo add stable http://mirror.azure.cn/kubernetes/charts
  script:
  - export API_VERSION=$(cat chart/Chart.yaml | grep apiVersion | cut -d\  -f2)
  - export DOCKER_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  - docker build -t ${DOCKER_REGISTRY_IMAGE} .
  - docker push ${DOCKER_REGISTRY_IMAGE}
  - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  - helm dep build chart
  - helm uninstall $KUBE_NAMESPACE || true
  - >
    helm install $KUBE_NAMESPACE chart --namespace $KUBE_NAMESPACE
    --set "nameOverride=$KUBE_NAMESPACE"
    --set "ingress.enabled=true"
    --set "ingress.hosts[0].host=${KUBE_NAMESPACE}-${API_VERSION}.env.bdaa.pro"
    --set "ingress.hosts[0].paths[0]=/"
    --set "image.repository=${CI_REGISTRY_IMAGE}"
    --set "image.tag=${CI_COMMIT_REF_NAME}"
    --set "image.pullPolicy=Always"
    --set "dockercfg=$(cat /root/.docker/config.json | base64 | tr -d '\n')"
    --set "ingress.annotations=null"
  environment:
    name: review/${CI_COMMIT_REF_NAME}
    url: https://$KUBE_NAMESPACE.env.bdaa.pro
    on_stop: stop_review
    auto_stop_in: 1 week
stop_review:
  stage: review
  image: registry.git.bdaa.pro:4567/yxonic/bdaa-deploy-image:v3.0.2
  script: helm uninstall $KUBE_NAMESPACE || true
  when: manual
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/${CI_COMMIT_REF_NAME}
    action: stop

production:
  stage: production
  image: registry.git.bdaa.pro:4567/yxonic/bdaa-deploy-image:v3.0.2
  before_script:
  - helm repo add stable http://mirror.azure.cn/kubernetes/charts
  script:
  - export API_VERSION=$(cat chart/Chart.yaml | grep apiVersion | cut -d\  -f2)
  - export DOCKER_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE}:${API_VERSION}
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  - docker build -t ${DOCKER_REGISTRY_IMAGE} .
  - docker push ${DOCKER_REGISTRY_IMAGE}
  - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  - helm dep build chart
  - helm uninstall $KUBE_NAMESPACE-$API_VERSION || true
  - >
    helm install $KUBE_NAMESPACE-$API_VERSION chart --namespace $KUBE_NAMESPACE
    --set "nameOverride=$KUBE_NAMESPACE-$API_VERSION"
    --set "ingress.enabled=true"
    --set "ingress.hosts[0].host=${KUBE_NAMESPACE}-${API_VERSION}.env.bdaa.pro"
    --set "ingress.hosts[0].paths[0]=/"
    --set "image.repository=${CI_REGISTRY_IMAGE}"
    --set "image.tag=${API_VERSION}"
    --set "image.pullPolicy=Always"
    --set "dockercfg=$(cat /root/.docker/config.json | base64 | tr -d '\n')"
    --set "ingress.annotations=null"
  environment:
    name: production
    url: https://$KUBE_NAMESPACE.env.bdaa.pro
  only:
    refs:
    - master
    kubernetes: active
  when: manual

