cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - staging
  - production

build:
  image: node:lts
  stage: build
  script:
    - npm config set unsafe-perm true
    - npm install -g cnpm --registry=https://registry.npm.taobao.org
    - cnpm install
    # code style check
    - npm run lint
    #####
    # build scripts (such as webpack) goes here
    ###
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  image: node:lts-alpine
  stage: test
  script:
    # - sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
    # - apk add openjdk8-jre
    - npm config set unsafe-perm true
    - npm install -g cnpm --registry=https://registry.npm.taobao.org
    - cnpm install -D
    #####
    # test scripts (such as jest) goes here
    ###
    - npm run unit

staging:
  stage: staging
  image: registry.git.bdaa.pro:4567/yxonic/bdaa-deploy-image:v3.0.2
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - helm repo add stable https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts
    - helm version
  script:
    - docker build -t ${CI_REGISTRY_IMAGE} .
    - docker push ${CI_REGISTRY_IMAGE}
    - helm uninstall $KUBE_NAMESPACE || true
    - >
      helm install $KUBE_NAMESPACE chart --namespace $KUBE_NAMESPACE
      --set "nameOverride=$KUBE_NAMESPACE"
      --set "ingress.enabled=true"
      --set "ingress.hosts[0].host=$KUBE_NAMESPACE.env.bdaa.pro"
      --set "ingress.hosts[0].paths[0]=/"
      --set "image.repository=${CI_REGISTRY_IMAGE}"
      --set "image.tag=latest"
      --set "image.pullPolicy=Always"
      --set "pullSecretName=pull-secret"
      --set "dockercfg=$(cat /root/.docker/config.json | base64 | tr -d '\n')"
  environment:
    name: staging
    url: https://$KUBE_NAMESPACE.env.bdaa.pro
  only:
    refs:
      - master
    kubernetes: active

production:
  stage: production
  image: registry.git.bdaa.pro:4567/yxonic/bdaa-deploy-image:v3.0.2
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - helm repo add stable https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:stable .
    - docker push ${CI_REGISTRY_IMAGE}:stable
    - helm uninstall $KUBE_NAMESPACE || true
    - >
      helm install $KUBE_NAMESPACE chart --namespace $KUBE_NAMESPACE
      --set "nameOverride=$KUBE_NAMESPACE"
      --set "ingress.enabled=true"
      --set "ingress.hosts[0].host=$KUBE_NAMESPACE.env.bdaa.pro"
      --set "ingress.hosts[0].paths[0]=/"
      --set "image.repository=${CI_REGISTRY_IMAGE}"
      --set "image.tag=stable"
      --set "image.pullPolicy=Always"
      --set "pullSecretName=pull-secret"
      --set "dockercfg=$(cat /root/.docker/config.json | base64 | tr -d '\n')"
  environment:
    name: production
    url: https://$KUBE_NAMESPACE.env.bdaa.pro
  when: manual
  only:
    refs:
      - master
    kubernetes: active
